### ISSUE TITLE
delayMicroseconds should accept an ulong parameter and not be limited to 65k microseconds

### ISSUE THREAD

**Issue by duhanebel** [Z-Wave-Me/Z-Uno-G2-Core#4]
I've notice that [delayMicroseconds](https://github.com/Z-Wave-Me/Z-Uno-G2-Core/blob/56a36da25f04cb18745654ee5b6c9c0e2dd67e56/hardware/arduino/zunoG2/cores/LLCore/LLCore.c#L668)' parameter is limited to 16bit precision. Shouldn't this be an `dword`/`ulong` instead?

**Comment by PoltoS** [comment]
This can of course be easily changed. But why not to use delay in for time larger than 65ms?

Agree, that with sword the code will be more universal. You can make a PR with a different branch staring from the original master. We apply it

**Comment by duhanebel** [comment]
I'm not sure `delay` would work. I'm sending data over RF433 and the protocol requires very specific timing (in this case 89565ms at the end of each frame). I haven't tested it but I think calling `delayMicroseconds` multiple times or using `delay` will introduce unwanted interval and the communication would fail.
I'll prepare a quick patch and send it over.

**Comment by amatilda** [comment]
Closing due to no problem
