### ISSUE TITLE
3.0.12 B6 Sketch not compiling due to ZUNO_SWITCH_COLOR

### ISSUE THREAD

**Issue by TheMasterofBlubb** [Z-Wave-Me/Z-Uno-G2-Core#8]
```
Arduino15\packages\Z-Uno2 (Beta)\hardware\zw_cm4f\3.0.12\cores\ZWSupport\ZWCCSwitchMultilevel.cpp: In function 'int32_t zuno_SwitchMultilevelUniversalGetter1P(byte)':

Arduino15\packages\Z-Uno2 (Beta)\hardware\zw_cm4f\3.0.12\cores\ZWSupport\ZWCCSwitchMultilevel.cpp:28:12: error: 'zunoSwitchColorSaveGet' was not declared in this scope
```

**Comment by TheMasterofBlubb** [comment]
Hi Pavel,

If i dont forget i can send you the specific sketch, but the issue was present at the most barebone sketch too, so a static configuration of 2 channels 1 Multilevel and 1 Color switch and their according event handlers. That creates the issue of using the Color switch flag and the multilevel switch.

Holen Sie sich Outlook für Android<https://aka.ms/ghei36>
________________________________

**Comment by amatilda** [comment]
Yes, I see there is a problem.
Thank you for reporting this.

The next update will fix it.

What would work for you now - add the following lines to the ZWCCSwitchMultilevel.cpp file:

`
void zunoSwitchColorSaveSet(uint8_t channel, void *value);
uint8_t zunoSwitchColorSaveGet(uint8_t channel);
`

To make it look like this:

`
#include "Arduino.h"
#include "ZWSupport.h"
#include "ZWCCTimer.h"
#include "ZWCCSwitchMultilevel.h"
#include "ZWCCBasic.h"
#include "ZWCCSuperVision.h"

void zunoSwitchColorSaveSet(uint8_t channel, void *value);
uint8_t zunoSwitchColorSaveGet(uint8_t channel);
`

**Comment by TheMasterofBlubb** [comment]
Will test it later today and give you the result

Holen Sie sich Outlook für Android<https://aka.ms/ghei36>
________________________________

**Comment by amatilda** [comment]
In the file ZWSupport.c on line 832 replace #ifdef WITH_CC_SWITCHCOLOR with #ifdef WITH_CC_SWITCH_COLOR

In file ZWCCSwitchColor.c on line 7 #ifdef WITH_CC_SWITCHCOLOR replace with #ifdef WITH_CC_SWITCH_COLOR

**Comment by TheMasterofBlubb** [comment]
That fixed compilation
